include:
  - local: /.gitlab/build-ci.yml
  - local: /.gitlab/security-ci.yml
  - local: /.gitlab/secret-ci.yml
  - local: /.gitlab/tag-ci.yml
  - local: /.gitlab/publish-ci.yml
stages:
  - test
  - release
  - publish
build:
  extends: .build
security:
  extends: .security
  needs:
    - build
secret:
  extends: .secret
.tag_base:
  extends: .tag
  needs:
    - build
    - security
    - secret
tag:major:
  extends: .tag_base
tag:minor:
  extends: .tag_base
tag:patch:
  extends: .tag_base
publish:
  extends: .publish
