include:
  - local: /.gitlab/security-ci.yml
  - local: /.gitlab/secret-ci.yml
  - local: /.gitlab/tag-ci.yml
stages:
  - test
  - release
build:
  stage: test
  image: golang:1.21-alpine
  before_script:
    - apk add curl
  script:
    - |
      cd docker-gen
      ./build
  artifacts:
    name: docker-gen.$CI_COMMIT_SHORT_SHA
    paths:
      - docker-gen/docker-gen
    expire_in: 10 mins
security:
  extends: .security
  needs:
    - build
secret:
  extends: .secret
.tag_base:
  extends: .tag
  needs:
    - build
    - security
    - secret
tag:major:
  extends: .tag_base
tag:minor:
  extends: .tag_base
tag:patch:
  extends: .tag_base
