#!/bin/bash
set -e
rlz="$1"
[ -f "${rlz}" ]
[ -f "${rlz}.sha256" ]
echo "deploy $rlz"
sha256sum -c "${rlz}.sha256"
tmp=$(mktemp -d)
trap "rm -rf $tmp 2>/dev/null" EXIT INT TERM
tar -xvf "$rlz" -C $tmp
[ -f $tmp/metadata ] && [ -f $tmp/context/docker-compose.yml ] && [ -d $tmp/images ]
. $tmp/metadata
. /etc/compose-dirs.conf
[ -n "$app" ]
echo "$app" | grep -q '[-_a-zA-Z0-9]'
[ -n "$target_env" ]
echo "$target_env" | grep -q -E '(dev|integ|recette|prod)'
if [ $(ls $tmp/images/*.tar.gz 2>/dev/null|wc -l) -gt 0 ]; then
  for image in $tmp/images/*.tar.gz; do
    zcat $image | docker image load
    rm $image
  done
fi
cd "$compose_dir"
mkdir -p $app/$target_env
mv $tmp/context/docker-compose.yml $app/$target_env/orig.yml
cp $tmp/context/* $app/$target_env/ 2>/dev/null || true
cd $app/$target_env/
cat > proxy.yml <<EOF
version: '2.4'
networks:
  "proxy":
    external:
      name: "proxy_network"
services:
EOF
domain=$(sed -r -n '/DEFAULT_HOST/s/.*=(.*)"/\1/p' ${compose_dir}/proxy/docker-compose.yml)
[ "$target_env" = "prod" ] && suffix=.${domain} || suffix=-${target_env}.${domain}
for svc in $(docker-compose -f orig.yml config --services); do
  vhost_var=${svc}_base_vhost
  vhost=${!vhost_var}
  port_var=${svc}_vhost_port
  port=${!port_var:-80}
  if [ -n "$vhost" ]; then
    cat >> proxy.yml <<EOF
  $svc:
    environment:
      - "VIRTUAL_HOST=${vhost}${suffix}"
      - "LETSENCRYPT_HOST=${vhost}${suffix}"
      - "VIRTUAL_PORT=${port}"
    networks:
      - "proxy"
EOF
  fi
done
docker-compose -f orig.yml -f proxy.yml config > docker-compose.yml
cd "$compose_dir"
grep -q "^${app}/${target_env}:" $deps_file && sed -r -i "/^${app}\/${target_env}:/d" $deps_file
echo "${app}/${target_env}:proxy" >> $deps_file
sudo compose-dirs update
sudo systemctl restart compose@$(systemd-escape --suffix service "${app}/${target_env}")
