#!/bin/sh
if [ "$1" = "deploy" ]; then
  for f in /etc/capp/users/*; do
    u=$(basename "$f")
    while IFS= read -r line; do echo "environment=\"SSH_USER=$u\" $line"; done <<< $(cat "$f")
  done
fi
