version: '2.4'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    networks:
      - "network"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d:ro
      - nginx-html:/usr/share/nginx/html:ro
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:ro
  docker-gen:
    image: jrdasm/docker-gen:0.7.5
    container_name: docker-gen
    environment:
      - "DEFAULT_HOST=${DEFAULT_HOST}"
    networks:
      - "network"
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:ro
      - nginx-conf:/etc/nginx/conf.d:rw
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.0.2
    container_name: le-gen
    environment:
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
      - "NGINX_DOCKER_GEN_CONTAINER=docker-gen"
      - "DEFAULT_EMAIL=${DEFAULT_EMAIL}"
    networks:
      - "network"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh:rw
      - nginx-conf:/etc/nginx/conf.d:rw
      - nginx-html:/usr/share/nginx/html:rw
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:rw
networks:
  "network":
volumes:
  "nginx-conf":
  "nginx-html":
  "acme":
