version: '2.4'
services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    networks:
      - "network"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d:ro
      - nginx-html:/usr/share/nginx/html:ro
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:ro
  docker-gen:
    #image: jwilder/docker-gen:0.7.3 until a new version with bugfixes is released (https://github.com/jwilder/docker-gen)
    # coderedcorp seems to maintain a more up-to-date version (https://github.com/coderedcorp/docker-gen)
    image: coderedcorp/docker-gen:0.7.5-cr1
    container_name: docker-gen
    entrypoint: ["/usr/local/bin/docker-gen-wrapper"]
    command: ["-notify-sighup", "nginx-proxy", "-watch", "-wait", "5s:30s", "/etc/docker-gen/templates/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]
    environment:
      - "DEFAULT_HOST=${DEFAULT_HOST}"
    networks:
      - "network"
    volumes:
      - ./docker-gen-wrapper:/usr/local/bin/docker-gen-wrapper:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:ro
      - nginx-conf:/etc/nginx/conf.d:rw
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.13
    container_name: le-gen
    environment:
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
      - "NGINX_DOCKER_GEN_CONTAINER=docker-gen"
      - "DEFAULT_EMAIL=${DEFAULT_EMAIL}"
    networks:
      - "network"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d:rw
      - nginx-html:/usr/share/nginx/html:rw
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:rw
networks:
  "network":
volumes:
  "nginx-conf":
  "nginx-html":
