version: '2.4'
services:
  nginx:
    build:
      context: nginx
    container_name: nginx-proxy
    networks:
      - "network"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d:ro
      - nginx-html:/usr/share/nginx/html:ro
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:ro
  gen:
    build:
      context: gen
      args:
        - DOCKER_GEN_VERSION=${DOCKER_GEN_VERSION}
    container_name: docker-gen
    environment:
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
      - "DEFAULT_HOST=${DEFAULT_HOST}"
    networks:
      - "network"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:ro
      - nginx-conf:/etc/proxy-conf.d:rw
  le:
    build:
      context: le
      args:
        - DOCKER_GEN_VERSION=${DOCKER_GEN_VERSION}
    environment:
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
      - "NGINX_DOCKER_GEN_CONTAINER=docker-gen"
      - "DEFAULT_EMAIL=${DEFAULT_EMAIL}"
    networks:
      - "network"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh:rw
      - nginx-conf:/etc/nginx/conf.d:rw
      - nginx-html:/usr/share/nginx/html:rw
      - /var/docker-volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /var/docker-volumes/nginx-proxy/certs:/etc/nginx/certs:rw
networks:
  "network":
volumes:
  "nginx-conf":
  "nginx-html":
  "acme":
