version: "2.4"
services:
  scp:
    build:
      context: ./build
      args:
        panubo_ver: 1.3.0
        image: sshd-scp
        environment:
          - "SCP_MODE=true"
          - "MOTD=Docker Compose Archives"
          - "SSH_USERS=dca:1000:1000"
        volumes:
          - "keys:/etc/ssh/keys:rw"
          - "./dca_keys_entrypoint:/etc/entrypoint.d/dca_keys:ro"
          - "/etc/capp/users:/etc/capp/users:ro"
          - "/etc/capp/rights:/etc/capp/rights:ro"
          - "/home/deploy/dca:/home/dca:rw"
        ports:
          - "0.0.0.0:122:22"
volumes:
  keys:
