services:
  scp:
    build:
      context: ./build
      args:
        panubo_ver: 1.9.0
    image: sshd-scp
    environment:
      - "SCP_MODE=true"
      - "MOTD=Docker Compose Archives"
      - "SSH_USERS=dca:1000:1000"
    volumes:
      - type: volume
        source: keys
        target: /etc/ssh/keys
        read_only: false
      - type: bind
        source: ./dca_keys_entrypoint
        target: /etc/entrypoint.d/dca_keys
        read_only: true
      - type: bind
        source: /etc/capp/users
        target: /etc/capp/users
        read_only: true
      - type: bind
        source: /etc/capp/rights
        target: /etc/capp/rights
        read_only: true
      - type: bind
        source: /home/deploy/dca
        target: /home/dca
        read_only: false
    ports:
      - target: 22
        published: 122
        protocol: tcp
        mode: host
volumes:
  keys:
